# common
addBtn = "//button[normalize-space()='Add']"
search = "//input[@type='text']"
submitBtn = "//button[text()=' Submit ']"

# Login page
eptwLogo = "//h1[contains(text(),'E-Permit to work')]"
unameField = "//input[@title='User ID']"
pwdField = "//input[@type='password']"
loginBtn = "//button[text()='Login ']"
invalidToast2 = "//span[text()='Invalid username/password']"
invalidToast = "//span[.='Invalid username/password']"

# Logout
profile = "//div[@class='user-picture image ng-star-inserted']"
logout = "//span[text()='Log out']"

# Dashboard page
qualifiedPerson_bar = "//canvas[@id='inventBar']"
permitCount = "//div[@class='col-lg-5 col-xl-5 chart-box-mg']"

# Management - Contractor
menuMgmtContractor = "//span[text()='Contractor']"
coNameTxt = "//input[@formcontrolname='contractor_name']"
coContactNoTxt = "//input[@formcontrolname='contact_num']"
coPICTxt = "//input[@formcontrolname='contact_pers']"
coEmailTxt = "//input[@formcontrolname='email']"
coAddressTxt = "//textarea[@formcontrolname='address']"
coRegNoTxt = "//input[@formcontrolname='reg_no']"
coAbrvTxt = "//input[@formcontrolname='short_code']"
coLogoBtn = "//input[@name='pic']"
coRegionBtn = "//button[text()='Select Region']"
coRegionCentral1 = "//nb-option[@id='nb-option-17']"
coRemarkTxt = "//textarea[@formcontrolname='remark']"
coTypeBtn = "//button[text()='Select Type']"
coTypeNonTP = "//nb-option[@id='nb-option-0']"
coTypeTP = "//nb-option[@id='nb-option-1']"
coTable = "//div[@class='table-wrap ng-star-inserted']"
coTable_name = "//div[@class='table-wrap ng-star-inserted']//tbody/tr/td[1]"
coTable_row = "//div[@class='table-wrap ng-star-inserted']//tbody/tr"
coTable_column = "//div[@class='table-wrap ng-star-inserted']//tbody/tr/td"

# Management - User page
menuMgmt = "//span[text()='Management']"
menuMgmtUser = "//span[text()='User']"
tableUser = "//table[@class='table table-hovered']"
tableUserName = "//table[@class='table table-hovered']//tbody/tr/td[2]"
tableUser_row = "//table[@class='table table-hovered']//tbody/tr"
tableUser_column = "//table[@class='table table-hovered']//tbody/tr/td"

# Management -  Create User
userRoleBtn = "//button[@type='button']"
userRoleFT = "//nb-option[.='Field Team']"
userRoleCA = "//nb-option[.='Contractor Admin']"
state = "//nb-select[@formcontrolname='state_id']"
state_kedah = "//nb-option[@id='nb-option-3']"
nameInput = "//input[@formcontrolname='full_name']"
emailInput = "//input[@formcontrolname='email']"
phoneNo = "//input[@formcontrolname='phone_no']"
idTypeBtn = "//button[@class='select-button placeholder empty']"
idTypePassport = "//nb-option[.='Passport']"
passportNoField = "//input[@formcontrolname='ic']"
passportExpDate = "//input[@formcontrolname='passport_expire_date']"
passportExpDateLabel = "//label[normalize-space()='Passport Expiry Date']"
passportPic = "//input[@formcontrolname='ic_img']"
appLetter = "//input[@formcontrolname='appoint_img']"
remarkField = "//textarea[@title='remark']"
cancelBtn = "//button[text()=' Cancel ']"
certBtn = "//i[@class='fas fa-plus']"
certTypeBtn = "//button[@class='select-button placeholder']"
certTypeAESP = "//nb-option[.='AESP']"
certTypeAGT = "//nb-option[.='AGT']"
certTypeNTMSP = "//nb-option[.='NTMSP']"
certStartLabel = "//label[normalize-space()='Start Date']"
certExpiryLabel = "//label[normalize-space()='Expiry Date']"
certStartDate = "//input[@formcontrolname='issue_date']"
calendarYear = "(//*[local-name()='rect'])[14]"
calendarYear2 = "(//*[local-name()='rect'])[16]"
date1 = "//div[.=' 1 ']"
calendarYear2025 = "//div[normalize-space()='2025']"
calendarMonth = "//div[.=' Nov ']"
calendarDay = "//div[.=' 30 ']"
certExpDate = "//input[@formcontrolname='expired_date']"
certPic = "//input[@name='certfile']"
addCertBtn = "//button[text()=' Add ']"
okBtn = "//button[text()='OK']"

useridTxt = "//input[@formcontrolname='username']"
contractorBtn = "//div[.='Select Contractor Company']"
contractorSearch = "//input[@placeholder='Search']"
contractorXYZ = "//label[text()='Contractor XYZ']"
contractorRegionBtn = "//span[.='Select Region']"
contractorRegionC1 = "//label[normalize-space()='CENTRAL 1 REGION']"

isPI = "//span[contains(text(),'Is PI?')]"
searchId = "(//*[name()='rect'])[14]"
superiorId = "//input[@formcontrolname='superior_id']"
superiorName = "//input[@formcontrolname='superior_name']"
superiorEmail = "//input[@formcontrolname='superior_email']"
permitType = "//nb-select[@formcontrolname='permit_type']"
typeCS = "//nb-option[@id='nb-option-18']"
typeHR = "//nb-option[@id='nb-option-19']"


# Reporting - Menu
menuReporting = "//span[text()='Reporting']"
menuReportingPermit = "//span[text()='Permit']"

# Reporting - Permit
date_filter = "//input[@formcontrolname='date_range']"
type_filter = "//angular2-multiselect[@formcontrolname='permit_type']//div[@class='c-btn']"
