# common
cs_menu = "//android.view.View[@bounds='[117,902][966,1136]']"
hr_menu = "//android.view.View[@bounds='[117,1172][966,1404]']"
ss_menu = "//android.widget.TextView[@text='SSTA / SSKA']"
offcs_menu = "//android.view.View[@bounds='[117,1833][966,2065]']"
offhr_menu = "//android.view.View[@bounds='[117,2100][1007,2286]']"
btn_back = "//android.widget.Button[@text='Back']"
btn_login = "//android.widget.Button[@text='Login']"
btn_next = "//android.widget.Button[@text='Next']"
btn_enter = "//android.widget.Button[@text='Enter']"
loginId_header = "//android.widget.TextView[@text='TMDD1XYZ123P1']"
copy_toggle = "//android.view.View[@bounds='[879,726][930,749]']"
btn_agree = "//android.widget.Button[@text='Agree']"
btn_exit = "//android.view.View[@text='exit Exit']"
btn_create = "//android.widget.Button[@text='Create']"
btn_submit = "//android.widget.Button[@text='Submit']"
btn_gps = "//android.widget.Button[@text='locate outline Locate']"
camera_permission = "com.android.permissioncontroller:id/permission_allow_button"
camera_shutter = "com.hihonor.camera:id/foot_black_background"
camera_shutterOK = "com.hihonor.camera:id/head_black_background"
created_permitNo = "//android.widget.TextView[@bounds='[96,871][864,912]']"
title_ProjectDetails = "//android.widget.TextView[@text='Project Details']"
contractTP = "//android.widget.Button[@text='TP (TP Ori)']"
contractNonTP = "//android.widget.Button[@text='Non TP (CNC Lite / RR)']"
state_johor = "//android.widget.Button[@text='Johor']"

# CS
cs_title = "//android.widget.TextView[@text='Confined Space']"
cs_userid = "//android.widget.EditText[@bounds='[117,1144][966,1233]']"
cs_pwd = "//android.widget.EditText[@bounds='[142,1254][905,1353]']"
cs_role = "//android.widget.Button[@index=2]"
role_ES = "//android.widget.Button[@text='Entry Supervisor']"
role_AE = "//android.widget.Button[@text='Authorize Entrant']"
role_SP = "//android.widget.Button[@text='Standby Person']"
role_AGT = "//android.widget.Button[@text='Authorize Gas Tester']"
role_PI = "//android.widget.Button[@text='Permit Issuer']"
newPermit_btn = "//android.widget.Button[@text='New Permit']"
tab_Active = "//android.widget.ToggleButton[@text='Active']"
tab_Terminated = "//android.widget.ToggleButton[@text='Terminated']"
tab_Closed = "//android.widget.ToggleButton[@text='Closed']"

# CS - Project Details
cs_lor = "//android.widget.EditText[@bounds='[132,813][951,902]']"
txt_csNo = "//android.widget.EditText[@bounds='[132,973][951,1062]']"
list_state = "//android.widget.Button[@bounds='[132,1141][951,1231]']"
list_contract = "//android.widget.Button[@bounds='[132,1320][951,1409]']"
txt_sv = "//android.widget.EditText[@bounds='[132,1488][951,1578]']"
txt_svPhone = "//android.widget.EditText[@bounds='[132,1651][951,1738]']"
gps_permission1 = "//android.widget.TextView[@text='Allow ePTW to access this device’s location?']"
gps_permission2 = "//android.widget.Button[@text='WHILE USING THE APP']"

# CS - Team Members
title_TeamMembers = "//android.widget.TextView[@text='Team Members']"
ae_count_btn = "//android.widget.Button[@bounds='[132,858][951,948]']"
ae_count_1 = "//android.widget.TextView[@text='1']"
ae_count_2 = "//android.widget.TextView[@text='2']"
ae_count_3 = "//android.widget.TextView[@text='3']"
ae_field = "//android.widget.EditText[@bounds='[173,1055][836,1093]']"
sp_field = "//android.widget.EditText[@bounds='[173,1266][836,1305]']"
agt_field = "//android.widget.EditText[@bounds='[173,1450][836,1488]']"
ae_search = "//android.widget.Image[@bounds='[872,1055][910,1093]']"
ae_member = "//android.widget.TextView[@text='user two']"
sp_search = "//android.widget.Image[@bounds='[872,1266][910,1302]']"
sp_member = "//android.widget.TextView[@text='user three']"
agt_search = "//android.widget.Image[@bounds='[872,1450][910,1486]']"
agt_member = "//android.widget.TextView[@text='user one']"

# CS - PI Selection
title_PiSelection = "//android.widget.TextView[@text='PI Selection']"
division_NMO = "//android.widget.RadioButton[@text='Network Management & Operation']"
region = "//android.widget.Button[@bounds='[84,1419][997,1509]']"
region_1 = "//android.widget.Button[@text='Central 1 Region']"
wilayah = "//android.widget.Button[@bounds='[84,1580][997,1672]']"
wilayah_sgor1 = "//android.widget.Button[@text='Selangor Barat']"
zone = "//android.widget.Button[@bounds='[84,1743][997,1833]']"
zone_bRaja = "//android.widget.Button[@text='Bukit Raja & K. Selangor']"
pi = "//android.widget.Button[@bounds='[84,1906][997,1996]']"
pi_name = "//android.widget.Button[@text='USER ELEVEN']"
pi_contactNo = "//android.view.View[@text='Contact No. 0119990000']"
call = "//android.widget.Image[@text='call outline']"

# CS - Work Category
title_WorkCategory = "//android.widget.TextView[@text='Work Category']"
hot_Welding = "//android.widget.TextView[@text='Welding']"
fireExtinguisher = "//android.widget.TextView[@text='Portable Fire Extinguisher']"
faceRespirator = "//android.widget.TextView[@text='Half Face Respirator With Cartridge']"
pic_fireExtinguisher = "//android.widget.TextView[@text='Fire Extinguisher']"
pic_faceRespirator = "//android.widget.TextView[@text='Half Face Respirator']"
pic_teamPhoto = "//android.view.View[@text='Team Photo Take team photo complete with PPE']"
objRecognition_txt = "//android.widget.TextView[@bounds='[81,889][999,927]']"


# HR
hr_title = "//android.widget.TextView[@text='High Risk']"
hr_role = "//android.widget.Button[@bounds='[140,948][943,1037]']"
hr_userid = "//android.widget.EditText[@bounds='[165,1075][918,1144]']"
hr_pwd = "//android.widget.EditText[@bounds='[165,1187][882,1256]']"


# SSTA SSKA
ss_title = "//android.widget.TextView[@text='SSTA/SSKA']"
ss_role = "//android.widget.Button[@bounds='[117,966][966,1052]']"
role_requestor = "//android.widget.Button[@text='Requestor']"
role_sv = "//android.widget.Button[@text='Supervisor']"
ss_userid = "//android.widget.EditText[@bounds='[117,1080][966,1167]']"
ss_pwd = "//android.widget.EditText[@bounds='[142,1187][905,1287]']"
btn_new = "//android.widget.Button[@text='New']"
btn_checklist = "//android.widget.Button[@bounds='[84,848][997,935]']"
checklist_sska = "//android.widget.Button[@bounds='[122,953][724,1075]']"
checklist_ssta = "//android.widget.Button[@bounds='[122,1075][724,1198]']"
btn_state = "//android.widget.Button[@bounds='[84,1029][997,1119]']"
ss_lor = "//android.widget.EditText[@bounds='[84,1205][997,1292]']"
ss_work = "//android.widget.EditText[@bounds='[84,1368][997,1458]']"
ss_divisionNMO = "//android.widget.TextView[@text='Network Management & Operation']"
ss_region = "//android.widget.Button[@bounds='[84,1376][997,1465]']"
ss_region1 = "//android.widget.Button[@text='Central 1 Region']"
ss_wilayah = "//android.widget.Button[@bounds='[84,1539][997,1626]']"
ss_wilayahSgorBarat = "//android.widget.Button[@text='Selangor Barat']"
ss_zone = "//android.widget.Button[@bounds='[84,1700][997,1789]']"
ss_zoneKlang = "//android.widget.Button[@text='Klang']"
ss_searchSV = "//android.widget.Image[@text='search outline']"
sv_name = "//android.widget.TextView[@text='USER ELEVEN']"
sv_contactNo = "//android.view.View[@text='Contact No. 0119990000']"
call = "//android.widget.Image[@text='call outline']"
title_Checklist = "//android.widget.TextView[@text='Checklist']"
checklist_type = "//android.widget.TextView[@bounds='[114,693][966,736]']"
checklist_lor = "//android.widget.TextView[@bounds='[114,746][966,790]']"
checklist_work = "//android.widget.TextView[@bounds='[114,800][966,843]']"
checklist_expand = "//android.widget.Image[@text='caret down outline']"
item1_avail = "//android.view.View[@bounds='[719,1119][787,1147]']"
item1_qty = "//android.widget.EditText[@bounds='[805,1111][923,1157]']"
item2_avail = "//android.view.View[@bounds='[719,1473][787,1501]']"
item2_qty = "//android.widget.EditText[@bounds='[805,1465][923,1511]']"
item_uploadImage = "//android.widget.Image[@text='duplicate outline']"

# Offline common
tenantTM = "//android.widget.Button[@text='TM do not delete (arfans)']"
companyXYZ = "//android.widget.Button[@text='Contractor XYZ']"
off_camera = "//android.widget.Image[@text='takephoto']"

# Offline CS
offcs_name = "//android.widget.EditText[@bounds='[117,1070][966,1159]']"
offcs_id = "//android.widget.EditText[@bounds='[117,1185][966,1274]']"
tenant = "//android.widget.Button[@bounds='[84,736][997,825]']"
company = "//android.widget.Button[@bounds='[84,920][997,1009]']"

offcs_lor = "//android.widget.EditText[@bounds='[84,1093][997,1182]']"
offcs_contract = "//android.widget.Button[@bounds='[84,1266][997,1356]']"
offcs_csNo = "//android.widget.EditText[@bounds='[84,1442][997,1532]']"
offcs_state = "//android.widget.Button[@bounds='[84,1616][997,1705]']"
offcs_sv = "//android.widget.EditText[@bounds='[84,1789][997,1878]']"
offcs_svPhone =  "//android.widget.EditText[@bounds='[84,1955][997,2042]']"
off_divNMO = "//android.widget.TextView[@text='NMO']"
off_region = "//android.widget.Button[@index='2']"
off_REGION1 = "//android.widget.Button[@text='CENTRAL 1 REGION']"
off_piName = "//android.widget.EditText[@bounds='[84,1884][841,1970]']"
off_piId = "//android.widget.EditText[@bounds='[84,1988][841,2075]']"

offcs_aeList = "//android.widget.Button[@bounds='[84,769][997,858]']"
offcs_ae1 = "//android.widget.Button[@bounds='[122,876][724,999]']"
offcs_ae2 = "//android.widget.Button[@bounds='[122,999][724,1121]']"
offcs_ae3 = "//android.widget.Button[@bounds='[122,1121][724,1243]']"
offcs_aeName = "//android.widget.EditText[@bounds='[84,948][841,1037]']"
offcs_aeId = "//android.widget.EditText[@bounds='[84,1052][841,1141]']"
offcs_aeCamera = ""
offcs_spName = ""
offcs_spId = ""
offcs_spCamera = ""
offcs_agtName = ""
offcs_agtId = ""
offcs_agtCamera = ""
offcs_esName = ""
offcs_esId = ""
offcs_esCamera = ""


# Offline HR
offhr_name = ""
offhr_id = ""
offhr_ptw1 = "//android.widget.Button[@text='PTW High Risk']"
offhr_ptw2 = "//android.widget.Button[@text='PTW High Risk Near High Voltage']"
offhr_state = "//android.widget.Button[@bounds='[84,1103][997,1192]']"
offhr_contract = "//android.widget.Button[@bounds='[84,1287][997,1374]']"
offhr_lor = "//android.widget.EditText[@bounds='[84,1460][997,1549]']"
offhr_location = "//android.widget.EditText[@bounds='[84,1623][997,1713]']"
offhr_duration = "//android.widget.Button[@bounds='[84,1975][997,2065]']"
offhr_1hour = "//android.widget.Button[@text='1 Hour']"
offhr_svName = ""
offhr_svId = ""
offhr_reqName = ""
offhr_reqId = ""







